version: '3'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker/web/Dockerfile.prod
        command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server"
        volumes: 
            - .:/portfolio01-app
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        stdin_open: true
        tty: true
        environment: 
            DB_ROOT_USERNAME: root
            DB_USERNAME: user
            DB_PASSWORD: password
            TZ: Asia/Tokyo
            # DB_HOST: db
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes: 
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        ports:
            - "80:80"
        depends_on: 
            - web

volumes:
    tmp:
    public:
    

