version: '3'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes: 
            - .:/portfolio01-app
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        stdin_open: true
        tty: true
        environment: 
            DB_ROOT_USERNAME: root
            DB_USERNAME: user
            DB_PASSWORD: password
            TZ: Asia/Tokyo
            DB_HOST: db
        depends_on: 
            - db
        
    db:
        image: mysql:8.0.31
        environment: 
            - MYSQL_DATABASE=portfolio01_app_development
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=pass
            - TZ=Asia/Tokyo
        ports: 
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - mysql-data:/var/lib/mysql
        
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes: 
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        ports:
            - "80:80"
        depends_on: 
            - web
        
volumes:
    mysql-data:
    tmp:
    public: