version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: bundle exec puma -C config/puma.rb -e production
        volumes: 
            - .:/portfolio01-app
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        ports: 
            - '3000:3000'
        depends_on: 
            - db
        stdin_open: true
        tty: true
        networks: 
            - portfolio01-app-network
        
    db:
        image: mysql:8.0.31
        environment: 
            - MYSQL_DATABASE=portfolio01_app_development
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=pass
        ports: 
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            # - ./mysql-confd:/etc/mysql/conf.d
            - mysql-data:/var/lib/mysql
        
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes: 
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        ports:
            - "80:80"
        depends_on: 
            - web
        networks: 
            - portfolio01-app-network

volumes: 
    # mysql-data:
    #     driver: local
    mysql-data:
    tmp:
    public:
    
networks: 
    portfolio01-app-network:
        external: true

